---
title: "Analysis of hsb2 Data"
output:
  html_document:
    df_print: paged
---

The hsb2 data are demographics and test scores for a randome sample of high school seniors in the nation. This will be an anlaysis of those scores.  

```{r include=FALSE}
library(here)
```

### The relationship of SES to math performance

```{r include=FALSE}
hsb2 <- read.csv(here("Data", "hsb2.csv"))
```

Here are side-by-side boxplots of math scores by SES levels. 

```{r echo=FALSE}
hsb2$ses  <-factor(hsb2$ses,
                   levels= 1:3,
                   labels = c("low","middle","high"),
                   ordered = TRUE)

boxplot(hsb2$math ~ hsb2$ses, 
        xlab = "SES Category",
        ylab = "Math Test Score",
        main = "Math Test Scores by SES Category")
```

Here are descriptive statistics (five-number summaries, means and sd)

```{r echo=FALSE}
tapply(hsb2$math, hsb2$ses,mean)
```


```{r echo=FALSE}
tapply(hsb2$math, hsb2$ses,fivenum)
```


```{r echo=FALSE}
tapply(hsb2$math, hsb2$ses,sd)
```

